DELETE http://localhost:8080/api/files/8b8d030d-c149-46e7-bbd8-d0197be932de
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiYWNjZXNzIiwiZnJlc2giOmZhbHNlLCJjc3JmIjoiNzM1MGY5NmEtNjNjZS00YzUxLThiMjEtYTZhZjYyOGNjNDUxIiwiaXNzIjoiU3R1ZHktU2F2dnkiLCJzdWIiOiJ3ZWk4OTEwMTNAZ21haWwuY29tIiwiZXhwIjoxNjkyMjk3NDM0LCJuYmYiOjE2OTEwODc4MzQsImlhdCI6MTY5MTA4NzgzNH0.NHvRc7PAS0wml-BCaML7D01JNTomN_4k5iWeMTovox4
###
GET http://localhost:8080/api/files/resources/graph/8b8d030d-c149-46e7-bbd8-d0197be932de
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiYWNjZXNzIiwiZnJlc2giOmZhbHNlLCJjc3JmIjoiNzM1MGY5NmEtNjNjZS00YzUxLThiMjEtYTZhZjYyOGNjNDUxIiwiaXNzIjoiU3R1ZHktU2F2dnkiLCJzdWIiOiJ3ZWk4OTEwMTNAZ21haWwuY29tIiwiZXhwIjoxNjkyMjk3NDM0LCJuYmYiOjE2OTEwODc4MzQsImlhdCI6MTY5MTA4NzgzNH0.NHvRc7PAS0wml-BCaML7D01JNTomN_4k5iWeMTovox4
