GET http://localhost:8080/api/files
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiYWNjZXNzIiwiZnJlc2giOmZhbHNlLCJjc3JmIjoiMjZiZGI1ZDYtNDRmYS00ZDlhLWJhODAtMmNmNjYyZGIwZTQ0IiwiaXNzIjoiU3R1ZHktU2F2dnkiLCJzdWIiOiJvcGVuODkxMDEzQGdtYWlsLmNvbSIsImV4cCI6MTY5MjMzOTkyNiwibmJmIjoxNjkxMTMwMzI2LCJpYXQiOjE2OTExMzAzMjYsImp0aSI6IjI4Zjg0ZGEwLWRjMmMtNDBjNy1iNDQyLWE2NjZhN2I4MDBiMSJ9.Z_8s3H9Zs3zUsNwRywUpH5ZL1roYerEumsy7Tpsulws
###
GET http://localhost:8080/api/files/resources/graph/8b8d030d-c149-46e7-bbd8-d0197be932de
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiYWNjZXNzIiwiZnJlc2giOmZhbHNlLCJjc3JmIjoiNzM1MGY5NmEtNjNjZS00YzUxLThiMjEtYTZhZjYyOGNjNDUxIiwiaXNzIjoiU3R1ZHktU2F2dnkiLCJzdWIiOiJ3ZWk4OTEwMTNAZ21haWwuY29tIiwiZXhwIjoxNjkyMjk3NDM0LCJuYmYiOjE2OTEwODc4MzQsImlhdCI6MTY5MTA4NzgzNH0.NHvRc7PAS0wml-BCaML7D01JNTomN_4k5iWeMTovox4
