version: '1'
services:
  go:
    build: .
    ports:
      - "8080:8080"
    environment:
      JWT_EXPIRE_DAYS: 14
      JWT_ISSUER: Study-Savvy
      JWT_SECRET: Wei891013

      MYSQL_DB: gorm_test
      MYSQL_HOST: mysql
      MYSQL_PASSWORD: Wei891013
      MYSQL_PORT: 3306
      MYSQL_USER: root

      PAGE_SIZE: 10

      REDIS_HOST: redis
      REDIS_PASSWORD: Wei891013
      REDIS_PORT: 6379
      REDIS_DB: 0

      CELERY_TASK: tasks

      INFLUXDB_HOST: influxdb
      INFLUXDB_PORT: 8086
      INFLUXDB_TOKEN: Wei891013
      INFLUXDB_ORG: Study-Savvy
      INFLUXDB_BUCKET: LogsBucket

      DIRECTORY_AUDIO: /audio
      DIRECTORY_GRAPH: /graph
    depends_on:
      - redis
      - mysql
      - influxdb

  redis:
    image: redis:latest
    command: redis-server --requirepass Wei891013

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=Wei891013
      - MYSQL_DATABASE=gorm_test

  grafana:
    image: grafana/grafana
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=wei
      - GF_SECURITY_ADMIN_PASSWORD=Wei891013
    volumes:
      - grafana-storage:/var/lib/grafana

  influxdb:
    image: influxdb:latest
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=wei
      - DOCKER_INFLUXDB_INIT_PASSWORD=Wei891013
      - DOCKER_INFLUXDB_INIT_ORG=Study-Savvy
      - DOCKER_INFLUXDB_INIT_BUCKET=LogsBucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=Wei891013
    volumes:
      - influxdb-storage:/var/lib/influxdb

volumes:
  grafana-storage:
  influxdb-storage: