version: '1'
services:
  go-server:
    build: .
    ports:
      - "8080:8080"
    environment:
      JWT_EXPIRE_DAYS: 14
      JWT_ISSUER: Study-Savvy
      JWT_SECRET: Wei891013

      MYSQL_DB: gorm_test
      MYSQL_IP: mysql
      MYSQL_PASSWORD: Wei891013
      MYSQL_PORT: 3306
      MYSQL_USER: root

      PAGE_SIZE: 10

      REDIS_IP: redis
      REDIS_PASSWORD: Wei891013
      REDIS_PORT: 6379
      REDIS_DB: 0

      CELERY_TASK: tasks

      DIRECTORY_AUDIO: /audio
      DIRECTORY_GRAPH: /graph
    depends_on:
      - redis
      - mysql

  redis:
    image: redis:latest
    command: redis-server --requirepass Wei891013

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=Wei891013
      - MYSQL_DATABASE=gorm_test