version: '1'
services:
  go:
    build: .
    ports:
      - "8080:8080"
    environment:
      JWT_EXPIRE_DAYS: 14
      JWT_ISSUER: DefaultIssuer
      JWT_SECRET: DefaultJwtSecret

      MYSQL_DB: DefaultDb
      MYSQL_HOST: mysql
      MYSQL_PASSWORD: DefaultPassword
      MYSQL_PORT: 3306
      MYSQL_USER: root

      PAGE_SIZE: 10

      REDIS_HOST: redis
      REDIS_PASSWORD: DefaultPassword
      REDIS_PORT: 6379
      REDIS_DB: 0

      CELERY_TASK: tasks

      INFLUXDB_HOST: influxdb
      INFLUXDB_PORT: 8086
      INFLUXDB_TOKEN: DefaultPassword
      INFLUXDB_ORG: DefaultOrg
      INFLUXDB_BUCKET: DefaultBucket

      DIRECTORY_AUDIO: /audio
      DIRECTORY_GRAPH: /graph
    depends_on:
      - redis
      - mysql
      - influxdb
    volumes:
      - logs_directory:/logs

  redis:
    image: redis:latest
    command: redis-server --requirepass DefaultPassword

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=DefaultPassword
      - MYSQL_DATABASE=DefaultDb

  grafana:
    image: grafana/grafana
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=DefaultUser
      - GF_SECURITY_ADMIN_PASSWORD=DefaultPassword
    volumes:
      - grafana-storage:/var/lib/grafana

  influxdb:
    image: influxdb:latest
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=DefaultUser
      - DOCKER_INFLUXDB_INIT_PASSWORD=DefaultPassword
      - DOCKER_INFLUXDB_INIT_ORG=DefaultOrg
      - DOCKER_INFLUXDB_INIT_BUCKET=DefaultBucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=DefaultPassword
    volumes:
      - influxdb-storage:/var/lib/influxdb

volumes:
  grafana-storage:
  influxdb-storage:
  logs_directory: