### Send POST request with json body
PUT http://localhost:8080/api/information/password_edit
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiYWNjZXNzIiwiZnJlc2giOmZhbHNlLCJjc3JmIjoiZjk4ZGZkOWQtY2QyNS00NTQwLTlkZTYtMTM5OTExNWYzMDFhIiwiaXNzIjoiU3R1ZHktU2F2dnkiLCJzdWIiOiJvcGVuODkxMDEzQGdtYWlsLmNvbSIsImV4cCI6MTY5MjE1OTYwMCwibmJmIjoxNjkwOTUwMDAwLCJpYXQiOjE2OTA5NTAwMDB9.wSBTxdvozAuYe0NBx3PdwqZjiM_uA_AzVpCsmMmUSyQ
Content-Type: application/json

{
  "gender": "male",
  "mail": "open891013@gmail.com",
  "password": "Wei891013",
  "name": "Wei"
}
