### Send POST request with json body
POST http://localhost:8080/api/login/app
Content-Type: application/json

{
  "gender": "male",
  "mail": "open891013@gmail.com",
  "password": "Wei89101",
  "name": "Wei"
}
