### ApiKey Set
PUT {{BASE_URL}}/api/Access_method/api_key
Authorization: Bearer {{EXAMPLE_JWT}}
Content-Type: application/json

{
  "api_key": "{{EXAMPLE_AES_KEY}}",
  "aes_key": "{{EXAMPLE_API_KEY}}"
}