POST {{BASE_URL}}/api/Predict/ASR
X-CSRF-Token: {{EXAMPLE_CSRF_TOKEN}}
Content-Type: multipart/form-data;boundary=BOUNDARY

--BOUNDARY
Content-Disposition: form-data; name="file"; filename="example.mp3"

Test file of audio

--BOUNDARY--
