### Password Edit
PUT {{BASE_URL}}/api/Information/password_edit
X-CSRF-Token: {{EXAMPLE_CSRF_TOKEN}}
Content-Type: application/json

{
  "original_pwd": "{{EXAMPLE_PASSWORD}}",
  "new_pwd": "{{EXAMPLE_EDIT_PASSWORD}}"
}