### Password Edit
PUT {{BASE_URL}}/api/information/password_edit
Authorization: Bearer {{EXAMPLE_JWT}}
Content-Type: application/json

{
  "original_pwd": "{{EXAMPLE_PASSWORD}}",
  "new_pwd": "{{EXAMPLE_EDIT_PASSWORD}}"
}